(() => {
  const $ = selector => document.querySelector(selector);
  const $$ = selector => [...document.querySelectorAll(selector)];
  const progress = () => { try { return JSON.parse(localStorage.getItem('entreDosMundosReadingProgress')) || {}; } catch { return {}; } };
  const read = () => { try { return JSON.parse(localStorage.getItem('entreDosMundosRead')) || []; } catch { return []; } };
  const reached = () => Math.max(1, (progress().chapter ?? 0) + 1, ...read().map(index => index + 1));

  const timeline = [
    [1,'Una partida inesperada','Méndez y Michelle se conocen dentro del videojuego.'],
    [10,'Del otro lado de la pantalla','La conexión comienza a convertirse en algo real.'],
    [20,'Nuestro verdadero hogar','Los tres descubren una forma nueva de sentirse familia.'],
    [30,'El precio del apellido','La familia de Méndez intenta decidir por él.'],
    [40,'Una puerta al pasado','El regreso de Elena transforma todo lo que Méndez creía saber.'],
    [49,'La desaparición de Gigi','La amenaza deja de ser únicamente económica.'],
    [58,'Fuego en el negocio','El peligro alcanza el mundo construido por Michelle.'],
    [61,'La confianza como arma','La aparente transformación de Dylan comienza a mostrar grietas.'],
    [65,'Una llave desde dentro','Alguien utiliza la confianza de Gigi para acercarse a los archivos.'],
    [70,'Veinticuatro horas','Origen abre una conversación directa con Méndez.'],
    [75,'La memoria equivocada','Las alianzas comienzan a romperse alrededor de una prueba cifrada.'],
    [80,'El imperio necesita un dueño','La junta activa una red mucho mayor que la empresa visible.']
  ];
  const clues = [
    [1,'Mich_27','Nombre de Michelle dentro del videojuego.'],
    [15,'El regreso de Dylan','Su aparición vuelve a conectar a Michelle con un pasado que quería dejar atrás.'],
    [29,'Elena','La madre de Méndez regresa con una versión distinta de la historia familiar.'],
    [42,'La fortuna robada','Documentos ocultos revelan que el imperio no se construyó limpiamente.'],
    [49,'La desaparición','Gigi se convierte en el centro de una amenaza calculada.'],
    [56,'El dispositivo','Los archivos conectan las decisiones del abuelo con otros miembros de la familia.'],
    [61,'El segundo teléfono','Una comunicación secreta demuestra que alguien trabaja desde dentro.'],
    [65,'La llave copiada','El acceso al estudio revela hasta dónde llega la manipulación.'],
    [70,'Origen','Un canal dentro del videojuego reclama una conexión con el padre de Méndez.'],
    [75,'La memoria cifrada','Tres voces protegen la prueba que todos quieren controlar.'],
    [78,'HEREDERO_02','El abuelo había preparado sustitutos antes de elegir a Méndez.'],
    [80,'Libro II','Una red secreta despierta cuando Méndez vuelve a la junta.']
  ];
  const evolved = {
    dylan:{at:61,role:'EL INFILTRADO',description:'Su regreso no nació del arrepentimiento. Se ganó la confianza de Michelle, Gigi y Méndez para obtener información y cobrar por cada traición.',quote:'«Mi lealtad nunca estuvo incluida.»'},
    padre:{at:63,role:'LA VOZ EN LAS SOMBRAS',description:'Una presencia vinculada al pasado de Méndez dirige movimientos desde lejos. Su identidad y sus alianzas todavía no están demostradas ante la familia.',quote:'«Todavía.»'},
    gigi:{at:65,role:'LA CONFIANZA HERIDA',description:'Gigi sigue siendo luminosa, pero empieza a descubrir que los adultos pueden utilizar incluso el cariño como una herramienta.',quote:'«Yo sí te conozco.»'}
  };

  function renderSpoilerSafe(){
    const level=reached();
    $$('.timeline-item').forEach(item=>{const unlocked=level>=Number(item.dataset.chapter);item.classList.toggle('locked',!unlocked);item.querySelector('p').textContent=unlocked?item.dataset.summary:'Continúa leyendo para desbloquear este momento.'});
    $$('.clue-card').forEach(item=>{const unlocked=level>=Number(item.dataset.chapter);item.classList.toggle('locked',!unlocked);item.querySelector('p').textContent=unlocked?item.dataset.summary:'Pista bloqueada para evitar spoilers.'});
    const note=$('#spoiler-progress');if(note)note.textContent=`Contenido visible según tu progreso: capítulo ${String(level).padStart(2,'0')}`;
  }
  const timelineEl=$('#timeline-list');if(timelineEl)timelineEl.innerHTML=timeline.map(([chapter,title,summary])=>`<article class="timeline-item" data-chapter="${chapter}" data-summary="${summary}"><span>${String(chapter).padStart(2,'0')}</span><div><h3>${title}</h3><p></p></div></article>`).join('');
  const clueEl=$('#clue-grid');if(clueEl)clueEl.innerHTML=clues.map(([chapter,title,summary])=>`<article class="clue-card" data-chapter="${chapter}" data-summary="${summary}"><small>CAPÍTULO ${String(chapter).padStart(2,'0')}</small><h3>${title}</h3><p></p></article>`).join('');
  renderSpoilerSafe();
  $('#clear-progress')?.addEventListener('click',()=>setTimeout(renderSpoilerSafe));
  $('#chapter-select')?.addEventListener('change',()=>setTimeout(renderSpoilerSafe));

  $$('[data-character]').forEach(button=>button.addEventListener('click',()=>{const update=evolved[button.dataset.character];if(!update||reached()<update.at)return;requestAnimationFrame(()=>{const role=$('#modal-role'),description=$('#modal-description'),quote=$('#modal-quote');if(role)role.textContent=update.role;if(description)description.textContent=update.description;if(quote)quote.textContent=update.quote})}));

  const focus=$('#focus-mode');if(focus)focus.addEventListener('click',()=>{const active=document.body.classList.toggle('focus-reading');focus.textContent=active?'Salir del modo lectura':'Modo sin distracciones';focus.setAttribute('aria-pressed',String(active))});
  const exitFocus=$('#focus-exit');if(exitFocus)exitFocus.addEventListener('click',()=>document.body.classList.remove('focus-reading'));

  const share=$('#share-chapter');if(share)share.addEventListener('click',async()=>{const number=Number($('#chapter-select').value)+1,url=`${location.origin}${location.pathname}?capitulo=${number}#leer`,title=`Entre dos mundos · Capítulo ${number}`;try{if(navigator.share)await navigator.share({title,url});else{await navigator.clipboard.writeText(url);share.textContent='Enlace copiado ✓';setTimeout(()=>share.textContent='Compartir capítulo',1800)}}catch{}});
  const requestedValue=new URLSearchParams(location.search).get('capitulo'),requested=Number(requestedValue);if(requestedValue!==null&&Number.isInteger(requested)&&requested>=1&&requested<=100&&$('#chapter-select'))setTimeout(()=>{$('#chapter-select').value=String(requested-1);$('#chapter-select').dispatchEvent(new Event('change'));history.replaceState(null,'',`?capitulo=${requested}#leer`)},80);

  const volume=$('#ambient-volume'),soundtrack=$('#soundtrack');if(volume)volume.addEventListener('input',event=>{soundtrack.volume=Number(event.target.value);localStorage.setItem('entreDosMundosVolume',event.target.value)});if(volume)volume.value=localStorage.getItem('entreDosMundosVolume')||'.32';
  const scene=$('#ambient-scene'),tracks={main:['public/audio/entre-dos-mundos.mp3','Entre dos mundos'],game:['public/audio/partida-nocturna.mp3','Partida nocturna'],rain:['public/audio/lluvia-en-la-ciudad.mp3','Lluvia en la ciudad'],tension:['public/audio/la-conspiracion.mp3','La conspiración']};if(scene){scene.value=localStorage.getItem('entreDosMundosSoundscape')||'main';const applyTrack=async(value,userAction=false)=>{const wasPlaying=!soundtrack.paused,[src,title]=tracks[value]||tracks.main;soundtrack.src=src;$('#track-title').textContent=title;localStorage.setItem('entreDosMundosSoundscape',value);if(wasPlaying||userAction)try{await soundtrack.play()}catch{}};applyTrack(scene.value);scene.addEventListener('change',event=>applyTrack(event.target.value,true))}
  const musicSettings=$('#music-settings'),ambientPanel=$('#ambient-control'),ambientClose=$('#ambient-close');const setMusicPanel=open=>{if(!ambientPanel||!musicSettings)return;ambientPanel.classList.toggle('open',open);musicSettings.setAttribute('aria-expanded',String(open));if(open)scene?.focus()};musicSettings?.addEventListener('click',()=>setMusicPanel(!ambientPanel.classList.contains('open')));ambientClose?.addEventListener('click',()=>setMusicPanel(false));document.addEventListener('keydown',event=>{if(event.key==='Escape')setMusicPanel(false)});document.addEventListener('pointerdown',event=>{if(matchMedia('(max-width:650px)').matches&&ambientPanel?.classList.contains('open')&&!ambientPanel.contains(event.target)&&event.target!==musicSettings)setMusicPanel(false)});

  const family=$('#family-reveal');if(family){$('#relaciones')?.appendChild(family);family.addEventListener('click',()=>{const map=$('.relationship-map');map.classList.toggle('expanded-tree');family.textContent=map.classList.contains('expanded-tree')?'Ocultar conexiones':'Explorar conexiones'})}

  const comments=$('#comments-container');if(comments){const script=document.createElement('script');script.src='https://utteranc.es/client.js';script.async=true;script.crossOrigin='anonymous';script.setAttribute('repo','TheArian20/entre-dos-mundos');script.setAttribute('issue-term','pathname');script.setAttribute('label','comentarios');script.setAttribute('theme','github-light');comments.appendChild(script);const fallback=document.createElement('p');fallback.className='comment-fallback';fallback.innerHTML='<a href="https://github.com/TheArian20/entre-dos-mundos/issues" target="_blank" rel="noreferrer">Abrir conversaciones en GitHub ↗</a>';comments.appendChild(fallback)}
  const nav=document.querySelector('nav'),reader=$('#leer'),book=$('#chapter'),settings=$('.reading-settings'),picker=$('.chapter-picker'),tools=$('.reader-tools');
  const settingsToggle=document.createElement('button');settingsToggle.id='reading-settings-toggle';settingsToggle.className='reading-settings-toggle';settingsToggle.textContent='Aa · Ajustes';settingsToggle.setAttribute('aria-expanded','false');settingsToggle.addEventListener('click',()=>{const open=reader.classList.toggle('settings-open');settingsToggle.setAttribute('aria-expanded',String(open));settingsToggle.textContent=open?'Cerrar ajustes':'Aa · Ajustes'});picker?.before(settingsToggle);if(picker&&settings)settings.prepend(picker);
  const topProgress=document.createElement('div');topProgress.className='top-reading-progress';topProgress.setAttribute('aria-hidden','true');topProgress.innerHTML='<i></i>';nav?.after(topProgress);
  let lastY=scrollY,scrollFrame;const updateReadingChrome=()=>{scrollFrame=0;if(!reader||!book)return;const rect=book.getBoundingClientRect(),inside=rect.top<innerHeight*.72&&rect.bottom>100,travel=Math.max(1,book.offsetHeight-innerHeight*.5),ratio=Math.max(0,Math.min(1,(scrollY-(rect.top+scrollY-100))/travel));document.body.classList.toggle('reading-active',inside);topProgress.classList.toggle('visible',inside);topProgress.firstElementChild.style.width=`${Math.round(ratio*100)}%`;const goingDown=scrollY>lastY+8;if(inside&&goingDown&&scrollY>120)nav?.classList.add('nav-hidden');else if(!goingDown||!inside)nav?.classList.remove('nav-hidden');lastY=scrollY};addEventListener('scroll',()=>{if(!scrollFrame)scrollFrame=requestAnimationFrame(updateReadingChrome)},{passive:true});updateReadingChrome();
  let wakeLock=null;const wakeButton=document.createElement('button');wakeButton.id='wake-lock';wakeButton.textContent='Mantener pantalla activa';wakeButton.setAttribute('aria-pressed','false');wakeButton.addEventListener('click',async()=>{if(wakeLock){await wakeLock.release();wakeLock=null;wakeButton.textContent='Mantener pantalla activa';wakeButton.setAttribute('aria-pressed','false');return}try{wakeLock=await navigator.wakeLock.request('screen');wakeButton.textContent='Pantalla siempre activa ✓';wakeButton.setAttribute('aria-pressed','true');wakeLock.addEventListener('release',()=>{wakeLock=null;wakeButton.textContent='Mantener pantalla activa';wakeButton.setAttribute('aria-pressed','false')})}catch{wakeButton.textContent='No disponible en este navegador'}});tools?.appendChild(wakeButton);
  const highlightKey='entreDosMundosHighlightsV2',highlighterButton=document.createElement('button'),highlighterPalette=document.createElement('div');
  let highlighterOn=false,activeHighlight='rose',pendingSelection=null,applyingHighlights=false,highlightSignature='';
  highlighterButton.id='highlighter-toggle';highlighterButton.className='highlighter-toggle';highlighterButton.innerHTML='<span>✎</span> Delineador';highlighterButton.setAttribute('aria-pressed','false');
  highlighterPalette.className='highlighter-palette';highlighterPalette.hidden=true;highlighterPalette.innerHTML='<small>SELECCIONA EL TEXTO Y ELIGE UN COLOR</small><div><button type="button" data-highlight="rose" class="active" aria-label="Resaltar en rosa"></button><button type="button" data-highlight="gold" aria-label="Resaltar en dorado"></button><button type="button" data-highlight="lilac" aria-label="Resaltar en lavanda"></button><button type="button" data-highlight="erase" class="eraser">Borrar</button></div><p>Para quitar una marca, toca directamente el texto resaltado.</p>';
  const getHighlights=()=>{try{return JSON.parse(localStorage.getItem(highlightKey))||{}}catch{return {}}},saveHighlights=value=>localStorage.setItem(highlightKey,JSON.stringify(value));
  const textPoint=(root,offset)=>{const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let node,passed=0;while(node=walker.nextNode()){if(passed+node.data.length>=offset)return[node,Math.max(0,offset-passed)];passed+=node.data.length}return[root,root.childNodes.length]};
  const unwrapHighlights=()=>{book.querySelectorAll('mark.reader-highlight').forEach(mark=>mark.replaceWith(...mark.childNodes));book.querySelectorAll('p').forEach(p=>p.normalize())};
  const applyHighlights=()=>{if(applyingHighlights)return;applyingHighlights=true;unwrapHighlights();const chapter=String(Number($('#chapter-select').value)),saved=getHighlights()[chapter];if(Array.isArray(saved)){const paragraphs=[...book.querySelectorAll('p')];[...saved].sort((a,b)=>b.paragraph-a.paragraph||b.start-a.start).forEach(item=>{const p=paragraphs[item.paragraph];if(!p||item.start>=item.end||item.end>p.textContent.length)return;const start=textPoint(p,item.start),end=textPoint(p,item.end),range=document.createRange(),mark=document.createElement('mark');mark.className='reader-highlight';mark.dataset.color=item.color;mark.dataset.highlightId=item.id;try{range.setStart(...start);range.setEnd(...end);mark.append(range.extractContents());range.insertNode(mark)}catch{}})}highlightSignature=`${chapter}|${book.textContent}`;applyingHighlights=false};
  const rememberSelection=()=>{if(!highlighterOn||applyingHighlights)return;const selection=getSelection();if(!selection||selection.isCollapsed||!selection.rangeCount)return;const range=selection.getRangeAt(0),startP=(range.startContainer.nodeType===3?range.startContainer.parentElement:range.startContainer).closest?.('p'),endP=(range.endContainer.nodeType===3?range.endContainer.parentElement:range.endContainer).closest?.('p');if(!startP||startP!==endP||!book.contains(startP))return;const beforeStart=document.createRange(),beforeEnd=document.createRange();beforeStart.selectNodeContents(startP);beforeStart.setEnd(range.startContainer,range.startOffset);beforeEnd.selectNodeContents(startP);beforeEnd.setEnd(range.endContainer,range.endOffset);pendingSelection={paragraph:[...book.querySelectorAll('p')].indexOf(startP),start:beforeStart.toString().length,end:beforeEnd.toString().length};highlighterPalette.classList.add('selection-ready')};
  document.addEventListener('selectionchange',rememberSelection);
  highlighterButton.addEventListener('click',()=>{highlighterOn=!highlighterOn;book.classList.toggle('highlighter-active',highlighterOn);highlighterPalette.hidden=!highlighterOn;highlighterButton.classList.toggle('active',highlighterOn);highlighterButton.setAttribute('aria-pressed',String(highlighterOn));highlighterButton.innerHTML=highlighterOn?'<span>✎</span> Cerrar delineador':'<span>✎</span> Delineador';if(!highlighterOn){pendingSelection=null;highlighterPalette.classList.remove('selection-ready');getSelection()?.removeAllRanges()}});
  highlighterPalette.addEventListener('click',event=>{const button=event.target.closest('[data-highlight]');if(!button)return;activeHighlight=button.dataset.highlight;highlighterPalette.querySelectorAll('button').forEach(item=>item.classList.toggle('active',item===button));if(!pendingSelection)return;const chapter=String(Number($('#chapter-select').value)),all=getHighlights();all[chapter]=Array.isArray(all[chapter])?all[chapter]:[];all[chapter]=all[chapter].filter(item=>item.paragraph!==pendingSelection.paragraph||item.end<=pendingSelection.start||item.start>=pendingSelection.end);if(activeHighlight!=='erase')all[chapter].push({...pendingSelection,color:activeHighlight,id:`${Date.now()}-${Math.random().toString(36).slice(2,7)}`});saveHighlights(all);pendingSelection=null;getSelection()?.removeAllRanges();highlighterPalette.classList.remove('selection-ready');applyHighlights()});
  book.addEventListener('click',event=>{if(!highlighterOn)return;const mark=event.target.closest('mark.reader-highlight');if(!mark)return;const chapter=String(Number($('#chapter-select').value)),all=getHighlights();all[chapter]=(all[chapter]||[]).filter(item=>item.id!==mark.dataset.highlightId);saveHighlights(all);applyHighlights()});
  tools?.append(highlighterButton);tools?.after(highlighterPalette);applyHighlights();
  const addCompletion=()=>{if(!book||book.querySelector('.chapter-complete'))return;const end=book.querySelector('.end');if(!end)return;const panel=document.createElement('section');panel.className='chapter-complete';const last=$('#next')?.disabled;panel.innerHTML=`<small>CAPÍTULO COMPLETADO</small><strong>${last?'Has llegado al último capítulo publicado':'¿Continuamos?'}</strong><button type="button">${last?'Próximamente':'Leer el siguiente capítulo →'}</button>`;panel.querySelector('button').disabled=!!last;panel.querySelector('button').addEventListener('click',()=>$('#next')?.click());end.replaceWith(panel)};new MutationObserver(()=>{addCompletion();const signature=`${String(Number($('#chapter-select').value))}|${book.textContent}`;if(signature!==highlightSignature)applyHighlights()}).observe(book,{childList:true});addCompletion();
  addEventListener('storage',()=>{renderSpoilerSafe();applyHighlights()});
})();
