(() => {
  const $ = selector => document.querySelector(selector);
  const $$ = selector => [...document.querySelectorAll(selector)];
  const progress = () => { try { return JSON.parse(localStorage.getItem('entreDosMundosReadingProgress')) || {}; } catch { return {}; } };
  const read = () => { try { return JSON.parse(localStorage.getItem('entreDosMundosRead')) || []; } catch { return []; } };
  const reached = () => Math.max(1, (progress().chapter ?? 0) + 1, ...read().map(index => index + 1));

  const timeline = [
    [1,'Una partida inesperada','Méndez y Michelle se conocen dentro del videojuego.'],
    [10,'Del otro lado de la pantalla','La conexión comienza a convertirse en algo real.'],
    [20,'Nuestro verdadero hogar','Los tres descubren una forma nueva de sentirse familia.'],
    [30,'El precio del apellido','La familia de Méndez intenta decidir por él.'],
    [40,'Una puerta al pasado','El regreso de Elena transforma todo lo que Méndez creía saber.'],
    [49,'La desaparición de Gigi','La amenaza deja de ser únicamente económica.'],
    [58,'Fuego en el negocio','El peligro alcanza el mundo construido por Michelle.'],
    [61,'La confianza como arma','La aparente transformación de Dylan comienza a mostrar grietas.'],
    [65,'Una llave desde dentro','Alguien utiliza la confianza de Gigi para acercarse a los archivos.'],
    [70,'Veinticuatro horas','Origen abre una conversación directa con Méndez.'],
    [75,'La memoria equivocada','Las alianzas comienzan a romperse alrededor de una prueba cifrada.'],
    [80,'El imperio necesita un dueño','La junta activa una red mucho mayor que la empresa visible.']
  ];
  const clues = [
    [1,'Mich_27','Nombre de Michelle dentro del videojuego.'],
    [15,'El regreso de Dylan','Su aparición vuelve a conectar a Michelle con un pasado que quería dejar atrás.'],
    [29,'Elena','La madre de Méndez regresa con una versión distinta de la historia familiar.'],
    [42,'La fortuna robada','Documentos ocultos revelan que el imperio no se construyó limpiamente.'],
    [49,'La desaparición','Gigi se convierte en el centro de una amenaza calculada.'],
    [56,'El dispositivo','Los archivos conectan las decisiones del abuelo con otros miembros de la familia.'],
    [61,'El segundo teléfono','Una comunicación secreta demuestra que alguien trabaja desde dentro.'],
    [65,'La llave copiada','El acceso al estudio revela hasta dónde llega la manipulación.'],
    [70,'Origen','Un canal dentro del videojuego reclama una conexión con el padre de Méndez.'],
    [75,'La memoria cifrada','Tres voces protegen la prueba que todos quieren controlar.'],
    [78,'HEREDERO_02','El abuelo había preparado sustitutos antes de elegir a Méndez.'],
    [80,'Libro II','Una red secreta despierta cuando Méndez vuelve a la junta.']
  ];
  const evolved = {
    dylan:{at:61,role:'EL INFILTRADO',description:'Su regreso no nació del arrepentimiento. Se ganó la confianza de Michelle, Gigi y Méndez para obtener información y cobrar por cada traición.',quote:'«Mi lealtad nunca estuvo incluida.»'},
    padre:{at:63,role:'LA VOZ EN LAS SOMBRAS',description:'Una presencia vinculada al pasado de Méndez dirige movimientos desde lejos. Su identidad y sus alianzas todavía no están demostradas ante la familia.',quote:'«Todavía.»'},
    gigi:{at:65,role:'LA CONFIANZA HERIDA',description:'Gigi sigue siendo luminosa, pero empieza a descubrir que los adultos pueden utilizar incluso el cariño como una herramienta.',quote:'«Yo sí te conozco.»'}
  };

  function renderSpoilerSafe(){
    const level=reached();
    $$('.timeline-item').forEach(item=>{const unlocked=level>=Number(item.dataset.chapter);item.classList.toggle('locked',!unlocked);item.querySelector('p').textContent=unlocked?item.dataset.summary:'Continúa leyendo para desbloquear este momento.'});
    $$('.clue-card').forEach(item=>{const unlocked=level>=Number(item.dataset.chapter);item.classList.toggle('locked',!unlocked);item.querySelector('p').textContent=unlocked?item.dataset.summary:'Pista bloqueada para evitar spoilers.'});
    const note=$('#spoiler-progress');if(note)note.textContent=`Contenido visible según tu progreso: capítulo ${String(level).padStart(2,'0')}`;
  }
  const timelineEl=$('#timeline-list');if(timelineEl)timelineEl.innerHTML=timeline.map(([chapter,title,summary])=>`<article class="timeline-item" data-chapter="${chapter}" data-summary="${summary}"><span>${String(chapter).padStart(2,'0')}</span><div><h3>${title}</h3><p></p></div></article>`).join('');
  const clueEl=$('#clue-grid');if(clueEl)clueEl.innerHTML=clues.map(([chapter,title,summary])=>`<article class="clue-card" data-chapter="${chapter}" data-summary="${summary}"><small>CAPÍTULO ${String(chapter).padStart(2,'0')}</small><h3>${title}</h3><p></p></article>`).join('');
  renderSpoilerSafe();
  $('#clear-progress')?.addEventListener('click',()=>setTimeout(renderSpoilerSafe));
  $('#chapter-select')?.addEventListener('change',()=>setTimeout(renderSpoilerSafe));

  $$('[data-character]').forEach(button=>button.addEventListener('click',()=>{const update=evolved[button.dataset.character];if(!update||reached()<update.at)return;requestAnimationFrame(()=>{const role=$('#modal-role'),description=$('#modal-description'),quote=$('#modal-quote');if(role)role.textContent=update.role;if(description)description.textContent=update.description;if(quote)quote.textContent=update.quote})}));

  const focus=$('#focus-mode');if(focus)focus.addEventListener('click',()=>{const active=document.body.classList.toggle('focus-reading');focus.textContent=active?'Salir del modo lectura':'Modo sin distracciones';focus.setAttribute('aria-pressed',String(active))});
  const exitFocus=$('#focus-exit');if(exitFocus)exitFocus.addEventListener('click',()=>document.body.classList.remove('focus-reading'));

  const share=$('#share-chapter');if(share)share.addEventListener('click',async()=>{const number=Number($('#chapter-select').value)+1,url=`${location.origin}${location.pathname}?capitulo=${number}#leer`,title=`Entre dos mundos · Capítulo ${number}`;try{if(navigator.share)await navigator.share({title,url});else{await navigator.clipboard.writeText(url);share.textContent='Enlace copiado ✓';setTimeout(()=>share.textContent='Compartir capítulo',1800)}}catch{}});
  const requestedValue=new URLSearchParams(location.search).get('capitulo'),requested=Number(requestedValue);if(requestedValue!==null&&Number.isInteger(requested)&&requested>=1&&requested<=100&&$('#chapter-select'))setTimeout(()=>{$('#chapter-select').value=String(requested-1);$('#chapter-select').dispatchEvent(new Event('change'));history.replaceState(null,'',`?capitulo=${requested}#leer`)},80);

  const volume=$('#ambient-volume'),soundtrack=$('#soundtrack');if(volume)volume.addEventListener('input',event=>{soundtrack.volume=Number(event.target.value);localStorage.setItem('entreDosMundosVolume',event.target.value)});if(volume)volume.value=localStorage.getItem('entreDosMundosVolume')||'.32';
  const scene=$('#ambient-scene'),tracks={main:['public/audio/entre-dos-mundos.mp3','Entre dos mundos'],game:['public/audio/partida-nocturna.mp3','Partida nocturna'],rain:['public/audio/lluvia-en-la-ciudad.mp3','Lluvia en la ciudad'],tension:['public/audio/la-conspiracion.mp3','La conspiración']};if(scene){scene.value=localStorage.getItem('entreDosMundosSoundscape')||'main';const applyTrack=async(value,userAction=false)=>{const wasPlaying=!soundtrack.paused,[src,title]=tracks[value]||tracks.main;soundtrack.src=src;$('#track-title').textContent=title;localStorage.setItem('entreDosMundosSoundscape',value);if(wasPlaying||userAction)try{await soundtrack.play()}catch{}};applyTrack(scene.value);scene.addEventListener('change',event=>applyTrack(event.target.value,true))}
  const musicSettings=$('#music-settings'),ambientPanel=$('#ambient-control'),ambientClose=$('#ambient-close');const setMusicPanel=open=>{if(!ambientPanel||!musicSettings)return;ambientPanel.classList.toggle('open',open);musicSettings.setAttribute('aria-expanded',String(open));if(open)scene?.focus()};musicSettings?.addEventListener('click',()=>setMusicPanel(!ambientPanel.classList.contains('open')));ambientClose?.addEventListener('click',()=>setMusicPanel(false));document.addEventListener('keydown',event=>{if(event.key==='Escape')setMusicPanel(false)});document.addEventListener('pointerdown',event=>{if(matchMedia('(max-width:650px)').matches&&ambientPanel?.classList.contains('open')&&!ambientPanel.contains(event.target)&&event.target!==musicSettings)setMusicPanel(false)});

  const family=$('#family-reveal');if(family){$('#relaciones')?.appendChild(family);family.addEventListener('click',()=>{const map=$('.relationship-map');map.classList.toggle('expanded-tree');family.textContent=map.classList.contains('expanded-tree')?'Ocultar conexiones':'Explorar conexiones'})}

  const comments=$('#comments-container');if(comments){const script=document.createElement('script');script.src='https://utteranc.es/client.js';script.async=true;script.crossOrigin='anonymous';script.setAttribute('repo','TheArian20/entre-dos-mundos');script.setAttribute('issue-term','pathname');script.setAttribute('label','comentarios');script.setAttribute('theme','github-light');comments.appendChild(script);const fallback=document.createElement('p');fallback.className='comment-fallback';fallback.innerHTML='<a href="https://github.com/TheArian20/entre-dos-mundos/issues" target="_blank" rel="noreferrer">Abrir conversaciones en GitHub ↗</a>';comments.appendChild(fallback)}
  const nav=document.querySelector('nav'),reader=$('#leer'),book=$('#chapter'),settings=$('.reading-settings'),picker=$('.chapter-picker'),tools=$('.reader-tools');
  const settingsToggle=document.createElement('button');settingsToggle.id='reading-settings-toggle';settingsToggle.className='reading-settings-toggle';settingsToggle.textContent='Aa · Ajustes';settingsToggle.setAttribute('aria-expanded','false');settingsToggle.addEventListener('click',()=>{const open=reader.classList.toggle('settings-open');settingsToggle.setAttribute('aria-expanded',String(open));settingsToggle.textContent=open?'Cerrar ajustes':'Aa · Ajustes'});picker?.before(settingsToggle);if(picker&&settings)settings.prepend(picker);
  const topProgress=document.createElement('div');topProgress.className='top-reading-progress';topProgress.setAttribute('aria-hidden','true');topProgress.innerHTML='<i></i>';nav?.after(topProgress);
  let lastY=scrollY,scrollFrame;const updateReadingChrome=()=>{scrollFrame=0;if(!reader||!book)return;const rect=book.getBoundingClientRect(),inside=rect.top<innerHeight*.72&&rect.bottom>100,travel=Math.max(1,book.offsetHeight-innerHeight*.5),ratio=Math.max(0,Math.min(1,(scrollY-(rect.top+scrollY-100))/travel));document.body.classList.toggle('reading-active',inside);topProgress.classList.toggle('visible',inside);topProgress.firstElementChild.style.width=`${Math.round(ratio*100)}%`;const goingDown=scrollY>lastY+8;if(inside&&goingDown&&scrollY>120)nav?.classList.add('nav-hidden');else if(!goingDown||!inside)nav?.classList.remove('nav-hidden');lastY=scrollY};addEventListener('scroll',()=>{if(!scrollFrame)scrollFrame=requestAnimationFrame(updateReadingChrome)},{passive:true});updateReadingChrome();
  let wakeLock=null;const wakeButton=document.createElement('button');wakeButton.id='wake-lock';wakeButton.textContent='Mantener pantalla activa';wakeButton.setAttribute('aria-pressed','false');wakeButton.addEventListener('click',async()=>{if(wakeLock){await wakeLock.release();wakeLock=null;wakeButton.textContent='Mantener pantalla activa';wakeButton.setAttribute('aria-pressed','false');return}try{wakeLock=await navigator.wakeLock.request('screen');wakeButton.textContent='Pantalla siempre activa ✓';wakeButton.setAttribute('aria-pressed','true');wakeLock.addEventListener('release',()=>{wakeLock=null;wakeButton.textContent='Mantener pantalla activa';wakeButton.setAttribute('aria-pressed','false')})}catch{wakeButton.textContent='No disponible en este navegador'}});tools?.appendChild(wakeButton);
  const bookmarkKey='entreDosMundosParagraphBookmark',bookmarkButton=document.createElement('button'),gotoBookmark=document.createElement('button'),removeBookmark=document.createElement('button'),bookmarkStatus=document.createElement('div');bookmarkButton.id='bookmark-position';bookmarkButton.textContent='🔖 Marcar aquí';gotoBookmark.id='goto-bookmark';gotoBookmark.textContent='Continuar desde el marcador';removeBookmark.id='remove-bookmark';removeBookmark.textContent='Quitar marcador';bookmarkStatus.className='bookmark-status';const savedBookmark=()=>{try{return JSON.parse(localStorage.getItem(bookmarkKey))}catch{return null}};const highlightBookmark=()=>{book.querySelectorAll('.bookmarked-paragraph').forEach(item=>item.classList.remove('bookmarked-paragraph'));const mark=savedBookmark(),chapter=Number($('#chapter-select').value);if(mark&&mark.chapter===chapter)book.querySelectorAll('p')[mark.paragraph]?.classList.add('bookmarked-paragraph')};const refreshBookmark=()=>{const mark=savedBookmark(),exists=!!mark;gotoBookmark.hidden=!exists;removeBookmark.hidden=!exists;bookmarkButton.textContent=exists&&mark.chapter===Number($('#chapter-select').value)?'🔖 Actualizar marcador':'🔖 Marcar aquí';bookmarkStatus.hidden=!exists;bookmarkStatus.innerHTML=exists?`<span>🔖</span><div><small>MARCADOR GUARDADO</small><strong>Capítulo ${String(mark.chapter+1).padStart(2,'0')} · párrafo ${mark.paragraph+1}</strong></div>`:'';highlightBookmark()};bookmarkButton.addEventListener('click',()=>{const paragraphs=[...book.querySelectorAll('p')];if(!paragraphs.length)return;const target=paragraphs.reduce((best,item)=>Math.abs(item.getBoundingClientRect().top-innerHeight*.42)<Math.abs(best.getBoundingClientRect().top-innerHeight*.42)?item:best,paragraphs[0]),paragraph=paragraphs.indexOf(target),chapter=Number($('#chapter-select').value);localStorage.setItem(bookmarkKey,JSON.stringify({chapter,paragraph}));refreshBookmark();target.classList.add('bookmark-flash');setTimeout(()=>target.classList.remove('bookmark-flash'),1200)});gotoBookmark.addEventListener('click',()=>{const mark=savedBookmark();if(!mark)return;$('#chapter-select').value=String(mark.chapter);$('#chapter-select').dispatchEvent(new Event('change'));setTimeout(()=>{const target=book.querySelectorAll('p')[mark.paragraph];target?.scrollIntoView({behavior:'smooth',block:'center'});target?.classList.add('bookmark-flash');setTimeout(()=>target?.classList.remove('bookmark-flash'),1400)},500)});removeBookmark.addEventListener('click',()=>{localStorage.removeItem(bookmarkKey);refreshBookmark()});tools?.append(bookmarkButton,gotoBookmark,removeBookmark);tools?.after(bookmarkStatus);refreshBookmark();
  const addCompletion=()=>{if(!book||book.querySelector('.chapter-complete'))return;const end=book.querySelector('.end');if(!end)return;const panel=document.createElement('section');panel.className='chapter-complete';const last=$('#next')?.disabled;panel.innerHTML=`<small>CAPÍTULO COMPLETADO</small><strong>${last?'Has llegado al último capítulo publicado':'¿Continuamos?'}</strong><button type="button">${last?'Próximamente':'Leer el siguiente capítulo →'}</button>`;panel.querySelector('button').disabled=!!last;panel.querySelector('button').addEventListener('click',()=>$('#next')?.click());end.replaceWith(panel)};new MutationObserver(()=>{addCompletion();refreshBookmark()}).observe(book,{childList:true});addCompletion();
  addEventListener('storage',()=>{renderSpoilerSafe();refreshBookmark()});
})();
