const characterProfiles={
 mendez:{name:'Méndez',role:'MENDEZ_01 · EL HEREDERO',age:'21 años',first:'Capítulo 1',relations:'Michelle, Gigi, Elena y sus abuelos',image:'public/characters/mendez.png',description:'Empresario brillante y heredero de una fortuna que nunca eligió. Sabe cerrar contratos imposibles, pero está aprendiendo las cosas sencillas que su familia nunca le permitió vivir.',quote:'«Quiero aprender a elegir una vida que sea mía.»'},
 michelle:{name:'Michelle',role:'MICH_27 · LA DISEÑADORA',age:'32 años',first:'Capítulo 1',relations:'Gigi, Méndez, su tío y Dylan',image:'public/characters/michelle.png',description:'Madre, trabajadora y diseñadora. Su honestidad atraviesa cualquier pantalla, aunque el pasado y las diferencias sociales pongan a prueba todo lo que ha construido.',quote:'«No necesito que me rescaten. Necesito que caminen conmigo.»'},
 gigi:{name:'Gigi',role:'GISELLE · LA LUZ',age:'9 años',first:'Capítulo 4',relations:'Michelle, Méndez y Dylan',image:'public/characters/gigi.png',description:'Curiosa, directa y luminosa. Conserva los ojos cálidos y el cabello rizado de Michelle. Suele comprender las emociones de los adultos antes que ellos mismos.',quote:'«Las familias también se eligen, ¿verdad?»'},
 dylan:{name:'Dylan',role:'EL PASADO',age:'Adulto',first:'Capítulo 5',relations:'Michelle y Gigi',image:'public/characters/dylan.png',description:'El padre ausente de Gigi. Regresa con explicaciones difíciles de comprobar y una capacidad inquietante para decir exactamente lo que los demás desean escuchar.',quote:'«Todos merecen otra oportunidad.»'},
 elena:{name:'Elena',role:'LA VERDAD',age:'Adulta',first:'Capítulo 29',relations:'Méndez y la familia empresarial',image:'public/characters/elena.png',description:'La madre de Méndez. Su regreso abre una puerta hacia la historia que los abuelos intentaron mantener cerrada.',quote:'«El silencio también puede ser una forma de mentira.»'},
 abuelo:{name:'El abuelo',role:'EL PODER',age:'Adulto mayor',first:'Capítulo 12',relations:'Méndez, la abuela y Elena',image:'public/characters/abuelo.png',description:'Patriarca del imperio familiar. Confundió protección con control y convirtió el talento de su nieto en el motor de una fortuna.',quote:'«Un apellido no se construye siguiendo al corazón.»'},
 abuela:{name:'La abuela',role:'EL APELLIDO',age:'Adulta mayor',first:'Capítulo 13',relations:'Méndez, el abuelo y Elena',image:'public/characters/abuela.png',description:'Elegante, severa y leal a las apariencias. Defiende el apellido familiar incluso cuando el precio amenaza con ser demasiado alto.',quote:'«Hay decisiones que una familia no puede permitirse.»'},
 tio:{name:'El tío de Michelle',role:'EL REFUGIO',age:'Adulto',first:'Capítulo 2',relations:'Michelle y Gigi',image:'public/characters/tio-michelle.png',description:'Compañero de trabajo y apoyo cotidiano de Michelle. Conoce el esfuerzo con el que ella levantó su vida y nunca convierte su ayuda en una deuda.',quote:'«El trabajo vale más cuando también deja espacio para vivir.»'},
 padre:{name:'Adrián',role:'EL PADRE · LA AMBICIÓN',age:'Adulto',first:'Capítulo 60',relations:'Méndez, el abuelo y Dylan',image:'public/characters/padre-mendez.png',description:'El padre de Méndez colaboró con el abuelo y convirtió a su propio hijo en una oportunidad económica. Sus alianzas responden al poder y al dinero.',quote:'«La familia también puede ser una inversión.»'},
 esteban:{name:'Esteban Valdés',role:'EL AUSENTE',age:'58 años',first:'Capítulo 91',relations:'Michelle, el tío, Gigi y Micaela',image:'public/characters/esteban.png',description:'El padre de Michelle fingió su muerte mientras reunía pruebas contra El Margen. Regresar no borra los años de abandono ni las decisiones que tomó sin consultar a su familia.',quote:'«Me dije que lo hacía por ti. También lo hacía por miedo.»'},
 micaela:{name:'Micaela Valdés',role:'LA PRIMERA LECTORA',age:'74 años',first:'Capítulo 98',relations:'Esteban, el tío, Michelle y Gigi',image:'public/characters/micaela.png',description:'La abuela materna de Michelle y una de las fundadoras de La Biblioteca. Observa a las familias como historias que pueden dirigirse durante generaciones.',quote:'«El primer libro debe cerrarse antes de conocer a la autora.»'},
 clara:{name:'Clara',role:'LA ESTRATEGA',age:'72 años',first:'Capítulo 81',relations:'Lucía, el abuelo y la red Continuidad',image:'public/characters/clara.png',description:'Antigua colaboradora del abuelo y responsable de una red humana de vigilancia, operadores y empresas. Preparó a Lucía para continuar un proyecto que ella misma ayudó a deformar.',quote:'«Querer no es relevante cuando fuiste preparada para algo mayor.»'},
 lucia:{name:'Lucía',role:'LA HEREDERA ELEGIDA',age:'27 años',first:'Capítulo 87',relations:'Clara, Dylan e Irene',image:'public/characters/lucia.png',description:'Nieta de Clara, educada para heredar su trabajo. Reconocer en Méndez el mismo encierro que vivió la obliga a decidir si seguirá obedeciendo.',quote:'«¿Qué ocurre si yo no quiero ser tu Continuidad?»'},
 irene:{name:'Irene',role:'LA INVESTIGADORA',age:'42 años',first:'Capítulo 61',relations:'Varela, Méndez, Michelle y la fiscalía',image:'public/characters/irene.png',description:'Investigadora firme y metódica. Convierte sospechas familiares en pruebas legales y protege a Gigi sin quitarle voz a Michelle.',quote:'«La diferencia es que conoces el plan y puedes negarte.»'},
 varela:{name:'Rogelio Varela',role:'EL CONTADOR',age:'68 años',first:'Capítulo 72',relations:'El padre de Michelle, el abuelo e Irene',image:'public/characters/varela.png',description:'Antiguo contador del imperio familiar. Conservó documentos y claves financieras que permiten demostrar cómo el abuelo y sus aliados ocultaron dinero y manipularon firmas.',quote:'«Una firma verdadera también puede sostener una mentira.»'},
 gabriel:{name:'Gabriel',role:'EL REEMPLAZO',age:'34 años',first:'Capítulo 78',relations:'El abuelo, Méndez y Adrián',image:'public/characters/gabriel.png',description:'Empresario preparado como heredero alternativo si Méndez rechazaba el imperio. Confunde haber sido elegido con tener derecho a controlar a los demás.',quote:'«A mí me eligió antes que a ustedes.»'}
};
const modal=document.querySelector('#character-modal');
function openCharacter(id){const item=characterProfiles[id];if(!item)return;document.querySelector('#modal-image').src=item.image;document.querySelector('#modal-image').alt=`Retrato de ${item.name}`;document.querySelector('#modal-role').textContent=item.role;document.querySelector('#modal-name').textContent=item.name;document.querySelector('#modal-description').textContent=item.description;document.querySelector('#modal-age').textContent=item.age;document.querySelector('#modal-first').textContent=item.first;document.querySelector('#modal-relations').textContent=item.relations;document.querySelector('#modal-quote').textContent=item.quote;modal.showModal()}
document.querySelectorAll('[data-character]').forEach(button=>button.addEventListener('click',()=>openCharacter(button.dataset.character)));document.querySelector('.modal-close').addEventListener('click',()=>modal.close());modal.addEventListener('click',event=>{if(event.target===modal)modal.close()});
const characterGrid=document.querySelector('#character-grid'),toggleCharacters=document.querySelector('#toggle-characters');toggleCharacters.addEventListener('click',()=>{const expanded=characterGrid.classList.toggle('expanded');toggleCharacters.setAttribute('aria-expanded',String(expanded));toggleCharacters.textContent=expanded?'Mostrar solo protagonistas ↑':'Ver todos los personajes ↓'});

const connectionText=document.querySelector('#connection-text'),connectionSequence=document.querySelector('.connection-sequence');const connectionMessages=['BUSCANDO PARTIDA…','JUGADOR ENCONTRADO','VOZ CONECTADA','CONEXIÓN ESTABLECIDA'];let connectionStep=0;function advanceConnection(){connectionText.textContent=connectionMessages[connectionStep];connectionSequence.classList.toggle('ready',connectionStep===connectionMessages.length-1);connectionStep=(connectionStep+1)%connectionMessages.length}advanceConnection();setInterval(advanceConnection,1900);
const hero=document.querySelector('.hero');if(hero&&matchMedia('(pointer:fine)').matches)hero.addEventListener('pointermove',event=>{const x=(event.clientX/innerWidth-.5)*8,y=(event.clientY/innerHeight-.5)*5;hero.style.backgroundPosition=`calc(50% + ${x}px) calc(50% + ${y}px)`});

const soundtrack=document.querySelector('#soundtrack'),soundToggle=document.querySelector('#sound-toggle');
soundtrack.volume=Number(localStorage.getItem('entreDosMundosVolume'))||.32;
function syncSoundButton(){const playing=!soundtrack.paused;soundToggle.classList.toggle('active',playing);soundToggle.textContent=playing?'❚❚':'▶';soundToggle.setAttribute('aria-label',playing?'Pausar música':'Reproducir música')}
soundToggle.addEventListener('click',async()=>{if(!soundtrack.paused){soundtrack.pause();return}try{await soundtrack.play()}catch{soundToggle.setAttribute('aria-label','Toca otra vez para reproducir música')}});
soundtrack.addEventListener('play',syncSoundButton);soundtrack.addEventListener('pause',syncSoundButton);soundtrack.addEventListener('ended',syncSoundButton);syncSoundButton();
