(()=>{
  'use strict';
  const q=(selector,root=document)=>root.querySelector(selector),qa=(selector,root=document)=>[...root.querySelectorAll(selector)];
  const book=q('#chapter'),reader=q('#leer'),select=q('#chapter-select'),settings=q('.reading-settings'),tools=q('.reader-tools'),site=q('#site');
  if(!book||!reader||!select)return;
  const chapters=()=>Array.isArray(window.CHAPTERS)?window.CHAPTERS:[],highlightKey='entreDosMundosHighlightsV2',settingsKey='entreDosMundosSettings',accessKey='entreDosMundosAccessibility';
  const readJSON=(key,fallback={})=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}},writeJSON=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
  const escape=value=>String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  function modal(id,title){const node=document.createElement('dialog');node.id=id;node.className='reader-modal';node.innerHTML=`<header class="reader-modal-head"><h2>${title}</h2><button class="reader-modal-close" aria-label="Cerrar">×</button></header><div class="reader-modal-body"></div>`;document.body.append(node);q('.reader-modal-close',node).onclick=()=>node.close();node.addEventListener('click',event=>{if(event.target===node)node.close()});return node}
  const openChapter=(index,highlightId)=>{select.value=String(index);select.dispatchEvent(new Event('change'));setTimeout(()=>{const target=highlightId?q(`[data-highlight-id="${CSS.escape(highlightId)}"]`,book):book;target?.scrollIntoView({behavior:'smooth',block:'center'});target?.classList.add('highlight-jump');setTimeout(()=>target?.classList.remove('highlight-jump'),1500)},300)};

  const actionBox=document.createElement('div');actionBox.className='reader-plus-actions';actionBox.innerHTML='<button id="open-highlights">✦ Mis resaltados</button><button id="open-book-search">⌕ Buscar en el libro</button><button id="open-mobile-index">☰ Índice completo</button><button id="open-accessibility">◉ Accesibilidad</button>';tools?.after(actionBox);

  const highlightsModal=modal('highlights-library','Mis resaltados');
  function renderHighlights(){const data=readJSON(highlightKey,{}),items=[];Object.entries(data).forEach(([chapter,marks])=>(Array.isArray(marks)?marks:[]).forEach(mark=>items.push({...mark,chapter:Number(chapter)})));const body=q('.reader-modal-body',highlightsModal);if(!items.length){body.innerHTML='<p class="reader-modal-empty">Todavía no has resaltado ninguna frase.</p>';return}body.innerHTML=items.sort((a,b)=>a.chapter-b.chapter||a.start-b.start).map(item=>{const chapter=chapters()[item.chapter],text=chapter?.paragraphs?.[item.paragraph]?.slice(item.start,item.end)||'Texto resaltado';return `<article class="highlight-card" data-id="${escape(item.id)}" data-chapter="${item.chapter}"><button class="highlight-delete" aria-label="Eliminar resaltado">×</button><small>CAPÍTULO ${String(item.chapter+1).padStart(2,'0')}</small><strong>${escape(chapter?.title||'Capítulo')}</strong><p><mark>${escape(text)}</mark></p><div class="highlight-note"><input value="${escape(item.note||'')}" placeholder="Añadir una nota a esta frase" aria-label="Nota del resaltado"><button>Guardar</button></div></article>`}).join('');qa('.highlight-card',body).forEach(card=>{card.querySelector('p').onclick=()=>{highlightsModal.close();openChapter(Number(card.dataset.chapter),card.dataset.id)};q('.highlight-delete',card).onclick=()=>{const all=readJSON(highlightKey,{}),chapter=String(card.dataset.chapter);all[chapter]=(all[chapter]||[]).filter(item=>item.id!==card.dataset.id);writeJSON(highlightKey,all);renderHighlights();select.dispatchEvent(new Event('change'))};q('.highlight-note button',card).onclick=()=>{const all=readJSON(highlightKey,{}),item=(all[String(card.dataset.chapter)]||[]).find(mark=>mark.id===card.dataset.id);if(item)item.note=q('input',card).value.trim();writeJSON(highlightKey,all);q('.highlight-note button',card).textContent='Guardado ✓'}})}
  q('#open-highlights').onclick=()=>{renderHighlights();highlightsModal.showModal()};

  const searchModal=modal('book-search-modal','Buscar en el libro');q('.reader-modal-body',searchModal).innerHTML='<form class="book-search"><input type="search" placeholder="Nombre, frase o acontecimiento" aria-label="Buscar texto"><button>Buscar</button></form><div class="search-results"><p class="reader-modal-empty">Escribe una palabra o frase.</p></div>';
  function searchBook(query){const results=q('.search-results',searchModal),needle=query.trim().toLocaleLowerCase('es');if(needle.length<2){results.innerHTML='<p class="reader-modal-empty">Escribe al menos dos letras.</p>';return}const matches=[];chapters().forEach((chapter,index)=>chapter.paragraphs.forEach((paragraph,pIndex)=>{const normalized=paragraph.replace(/\*\*/g,'');if(normalized.toLocaleLowerCase('es').includes(needle))matches.push({chapter,index,pIndex,text:normalized})}));results.innerHTML=matches.length?matches.slice(0,80).map(item=>`<button class="search-result" data-chapter="${item.index}" data-paragraph="${item.pIndex}"><small>CAPÍTULO ${String(item.index+1).padStart(2,'0')}</small><strong>${escape(item.chapter.title)}</strong><p>${escape(item.text.length>190?item.text.slice(0,187)+'…':item.text)}</p></button>`).join(''):'<p class="reader-modal-empty">No encontramos coincidencias.</p>';qa('.search-result',results).forEach(button=>button.onclick=()=>{searchModal.close();openChapter(Number(button.dataset.chapter));setTimeout(()=>book.querySelectorAll('p')[Number(button.dataset.paragraph)]?.scrollIntoView({behavior:'smooth',block:'center'}),420)})}
  q('.book-search',searchModal).onsubmit=event=>{event.preventDefault();searchBook(q('input',event.currentTarget).value)};q('#open-book-search').onclick=()=>{searchModal.showModal();setTimeout(()=>q('input',searchModal).focus(),50)};

  const indexModal=modal('mobile-index-modal','Índice de capítulos');q('.reader-modal-body',indexModal).innerHTML='<input class="mobile-index-search" type="search" placeholder="Buscar número o título"><div class="mobile-index-groups"></div>';
  function renderIndex(query=''){const current=Number(select.value),read=new Set(readJSON('entreDosMundosRead',[])),needle=query.toLocaleLowerCase('es'),groups=q('.mobile-index-groups',indexModal),ranges=[[0,19,'La conexión'],[20,39,'Elegir el pasado'],[40,59,'La amenaza'],[60,79,'La traición'],[80,99,'El origen']];groups.innerHTML=ranges.map(([start,end,title])=>{const entries=chapters().map((chapter,index)=>({chapter,index})).filter(({chapter,index})=>index>=start&&index<=end&&(!needle||String(index+1).includes(needle)||chapter.title.toLocaleLowerCase('es').includes(needle)));return entries.length?`<section><h3>${String(start+1).padStart(2,'0')}—${String(Math.min(end+1,chapters().length)).padStart(2,'0')} · ${title}</h3><div class="mobile-index-grid">${entries.map(({chapter,index})=>`<button class="mobile-index-item ${read.has(index)?'read':''} ${index===current?'current':''}" data-chapter="${index}"><b>${String(index+1).padStart(2,'0')}</b><span>${escape(chapter.title)}</span></button>`).join('')}</div></section>`:''}).join('');qa('[data-chapter]',groups).forEach(button=>button.onclick=()=>{indexModal.close();openChapter(Number(button.dataset.chapter))})}
  q('.mobile-index-search',indexModal).oninput=event=>renderIndex(event.target.value);q('#open-mobile-index').onclick=()=>{renderIndex();indexModal.showModal()};q('#dock-index')?.addEventListener('click',event=>{event.stopImmediatePropagation();renderIndex();indexModal.showModal()},{capture:true});

  const profile=document.createElement('section');profile.className='chapter-profile';q('.reading-settings-toggle')?.before(profile);
  const characters=['Méndez','Michelle','Gigi','Dylan','Elena','abuelo','abuela','tío','padre'];
  function updateProfile(){const index=Number(select.value),chapter=chapters()[index];if(!chapter)return;const text=chapter.paragraphs.join(' '),present=characters.filter(name=>new RegExp(name,'i').test(text)).map(name=>name[0].toUpperCase()+name.slice(1)),mood=index<20?'Partida nocturna':index<40?'Entre dos mundos':index<60?'Lluvia en la ciudad':'La conspiración',illustrated=!!q(`option[value="${index}"]`)&&[0,6,9,14,19,29,39,44,48,49,57,59,60,61,62,63,64,66,69,71,74,76,77,78,79].includes(index);profile.innerHTML=`<small>ANTES DE LEER · SIN SPOILERS</small><dl><div><dt>DURACIÓN</dt><dd>${chapter.minutes} minutos</dd></div><div><dt>PERSONAJES</dt><dd>${escape(present.slice(0,4).join(', ')||'Por descubrir')}</dd></div><div><dt>AMBIENTE</dt><dd>${mood}</dd></div><div><dt>ESCENA</dt><dd>${illustrated?'Capítulo ilustrado':'Lectura narrativa'}</dd></div></dl>`}
  select.addEventListener('change',()=>setTimeout(updateProfile));setTimeout(updateProfile,120);

  const advanced=document.createElement('div');advanced.className='advanced-reading';advanced.innerHTML='<label>TIPOGRAFÍA<select id="reader-font"><option value="literary">Literaria</option><option value="readable">Clásica legible</option><option value="sans">Sencilla</option></select></label><label>INTERLINEADO <input id="reader-line" type="range" min="1.5" max="2.15" step=".05" value="1.7"></label><label>ANCHO DEL TEXTO <input id="reader-width" type="range" min="560" max="820" step="20" value="690"></label>';settings?.append(advanced);
  function applyAdvanced(){const value=readJSON(settingsKey,{}),font=value.family||'literary';book.classList.toggle('font-sans',font==='sans');book.classList.toggle('font-readable',font==='readable');document.documentElement.style.setProperty('--reader-line',value.line||1.7);document.documentElement.style.setProperty('--reader-width',`${value.width||690}px`);q('#reader-font').value=font;q('#reader-line').value=value.line||1.7;q('#reader-width').value=value.width||690}
  const updateAdvanced=patch=>{writeJSON(settingsKey,{...readJSON(settingsKey,{}),...patch});applyAdvanced()};q('#reader-font').onchange=e=>updateAdvanced({family:e.target.value});q('#reader-line').oninput=e=>updateAdvanced({line:Number(e.target.value)});q('#reader-width').oninput=e=>updateAdvanced({width:Number(e.target.value)});applyAdvanced();
  const theme=q('#reading-theme');if(theme&&!q('option[value="contrast"]',theme)){theme.insertAdjacentHTML('beforeend','<option value="contrast">Alto contraste</option>');theme.addEventListener('change',event=>site.classList.toggle('high-contrast',event.target.value==='contrast'));if(readJSON(settingsKey,{}).theme==='contrast'){theme.value='contrast';site.classList.add('high-contrast')}}

  const accessModal=modal('accessibility-modal','Comodidad y accesibilidad');q('.reader-modal-body',accessModal).innerHTML='<div class="access-options"><label><input type="checkbox" data-access="reduceMotion"> Reducir movimientos y animaciones</label><label><input type="checkbox" data-access="highContrast"> Aumentar el contraste</label><label><input type="checkbox" data-access="largeTargets"> Botones táctiles más grandes</label></div><p>Los cambios se guardan solamente en este dispositivo.</p>';
  function applyAccess(){const value=readJSON(accessKey,{});document.documentElement.classList.toggle('reduce-motion',!!value.reduceMotion);site.classList.toggle('high-contrast',!!value.highContrast||readJSON(settingsKey,{}).theme==='contrast');site.classList.toggle('large-targets',!!value.largeTargets);qa('[data-access]',accessModal).forEach(input=>input.checked=!!value[input.dataset.access])}qa('[data-access]',accessModal).forEach(input=>input.onchange=()=>{const value=readJSON(accessKey,{});value[input.dataset.access]=input.checked;writeJSON(accessKey,value);applyAccess()});q('#open-accessibility').onclick=()=>{applyAccess();accessModal.showModal()};applyAccess();

  let touchStart=null;book.addEventListener('touchstart',event=>{if(event.touches.length===1)touchStart={x:event.touches[0].clientX,y:event.touches[0].clientY,time:Date.now()}},{passive:true});book.addEventListener('touchend',event=>{if(!touchStart||book.classList.contains('highlighter-active')||!getSelection()?.isCollapsed){touchStart=null;return}const touch=event.changedTouches[0],dx=touch.clientX-touchStart.x,dy=touch.clientY-touchStart.y;if(Date.now()-touchStart.time<650&&Math.abs(dx)>70&&Math.abs(dx)>Math.abs(dy)*1.5){const target=Number(select.value)+(dx<0?1:-1);if(target>=0&&target<chapters().length){select.value=String(target);select.dispatchEvent(new Event('change'));book.classList.add(dx<0?'swipe-left':'swipe-right');setTimeout(()=>book.classList.remove('swipe-left','swipe-right'),260)}}touchStart=null},{passive:true});
  const hint=document.createElement('p');hint.className='swipe-hint';hint.textContent='En el teléfono, desliza para cambiar de capítulo';book.after(hint);
  book.addEventListener('click',event=>{if(!document.body.classList.contains('focus-reading')||event.target.closest('mark')||!getSelection()?.isCollapsed)return;document.body.classList.toggle('focus-ui-visible')});q('#focus-exit')?.addEventListener('click',()=>document.body.classList.remove('focus-ui-visible'));
  qa('img').forEach(image=>{image.decoding='async';if(!image.closest('#inicio'))image.loading='lazy'});document.documentElement.lang='es';q('main')?.setAttribute('aria-label','Libro Entre dos mundos');
})();
