const $=selector=>document.querySelector(selector);
const $$=selector=>[...document.querySelectorAll(selector)];
const site=$('#site'),chapterView=$('#chapter'),chapterNumber=$('#chapter-number'),chapterTitle=$('#chapter-title'),readingTime=$('#reading-time'),chapterSelect=$('#chapter-select'),previous=$('#previous'),next=$('#next'),save=$('#save'),chapterGrid=$('#chapter-grid'),chapterEmpty=$('#chapter-empty'),chapterSearch=$('#chapter-search'),dock=$('#reading-dock'),dockBar=$('#dock-bar'),dockPercent=$('#dock-percent'),dockChapter=$('#dock-chapter');
const progressKey='entreDosMundosReadingProgress',settingsKey='entreDosMundosSettings',readKey='entreDosMundosRead',reactionKey='entreDosMundosReactions',notesKey='entreDosMundosNotes';
const chapterArt={0:['public/scenes/capitulo-01.png','La primera conexión'],6:['public/scenes/capitulo-07.png','La primera videollamada'],9:['public/scenes/capitulo-10.png','Del otro lado de la pantalla'],14:['public/scenes/capitulo-15.png','Dylan juega su última carta'],19:['public/scenes/capitulo-20.png','Nuestro verdadero hogar'],29:['public/scenes/capitulo-30.png','El precio del apellido'],39:['public/scenes/capitulo-40.png','Una puerta hacia el pasado'],44:['public/scenes/capitulo-45.png','El trato con Dylan'],48:['public/scenes/capitulo-49.png','La desaparición de Gigi'],49:['public/scenes/capitulo-50.png','La distancia necesaria'],57:['public/scenes/capitulo-58.png','Fuego en el negocio'],59:['public/scenes/capitulo-60.png','El precio de elegir']};
Object.assign(chapterArt,{60:['public/scenes/capitulo-61.png','La confianza como arma'],61:['public/scenes/capitulo-62.png','El precio de la traición'],62:['public/scenes/capitulo-63.png','La caja bajo el suelo'],63:['public/scenes/capitulo-64.png','La grieta perfecta'],64:['public/scenes/capitulo-65.png','Una llave desde dentro'],66:['public/scenes/capitulo-67.png','El depósito vacío'],69:['public/scenes/capitulo-70.png','Origen'],71:['public/scenes/capitulo-72.png','La segunda contraseña'],74:['public/scenes/capitulo-75.png','La memoria equivocada'],76:['public/scenes/capitulo-77.png','La cita de Dylan'],77:['public/scenes/capitulo-78.png','Heredero_02'],78:['public/scenes/capitulo-79.png','Las instrucciones del abuelo'],79:['public/scenes/capitulo-80.png','El imperio necesita un dueño']});
let publishedChapters=[],activeChapter=0,activeFilter='all',noteTimer;

function getJSON(key,fallback=null){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function setJSON(key,value){localStorage.setItem(key,JSON.stringify(value))}
function escapeHTML(value){return String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function inlineMarkup(value){return escapeHTML(value).replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>')}
function favorites(){return publishedChapters.map((_,index)=>index).filter(index=>localStorage.getItem(`chapter${index+1}`)==='saved')}
function readChapters(){return new Set(getJSON(readKey,[]))}
function isFavorite(index){return localStorage.getItem(`chapter${index+1}`)==='saved'}
function isRead(index){return readChapters().has(index)}
function chapterState(index){const progress=getJSON(progressKey);if(isRead(index))return '✓ Leído';if(progress?.chapter===index)return '• En curso';return ''}
function titleMarkup(title){const words=title.split(' ');return words.length>1?`${escapeHTML(words[0])}<br><em>${escapeHTML(words.slice(1).join(' '))}</em>`:`<em>${escapeHTML(title)}</em>`}

function illustrationMarkup(index){const art=chapterArt[index];return art?`<figure><img class="chapter-illustration" src="${art[0]}" alt="Ilustración de ${escapeHTML(art[1])}" loading="lazy"><figcaption>${escapeHTML(art[1])}</figcaption></figure>`:''}
function renderChapter(index,scroll=false,ratio=0){
 if(!publishedChapters.length)return;
 activeChapter=Math.max(0,Math.min(index,publishedChapters.length-1));
 const item=publishedChapters[activeChapter],paragraphs=item.paragraphs.map((p,i)=>`<p>${inlineMarkup(p)}</p>${i===0?illustrationMarkup(activeChapter):''}`).join('');
 chapterNumber.textContent=`CAPÍTULO ${String(activeChapter+1).padStart(2,'0')}`;chapterTitle.innerHTML=titleMarkup(item.title);readingTime.textContent=`Tiempo de lectura · ${item.minutes} min`;chapterView.innerHTML=paragraphs+`<div class="end">FIN DEL CAPÍTULO ${String(activeChapter+1).padStart(2,'0')}</div>`;chapterSelect.value=String(activeChapter);previous.disabled=activeChapter===0;next.disabled=activeChapter===publishedChapters.length-1;next.textContent=activeChapter===publishedChapters.length-1?'Continuará…':'Siguiente →';dockChapter.textContent=`Cap. ${String(activeChapter+1).padStart(2,'0')}`;
 refreshFavoriteButton();renderFeedback();
 if(scroll)requestAnimationFrame(()=>{const top=chapterView.getBoundingClientRect().top+scrollY-105,travel=Math.max(0,chapterView.offsetHeight-innerHeight*.45);scrollTo({top:top+travel*ratio,behavior:'smooth'});chapterView.focus({preventScroll:true})});
}
function refreshFavoriteButton(){save.textContent=isFavorite(activeChapter)?'♥ En favoritos':'♡ Añadir a favoritos'}
function updateStats(){const progress=getJSON(progressKey),read=readChapters().size,favs=favorites().length,start=progress?.chapter??0,minutes=publishedChapters.slice(start).reduce((sum,item)=>sum+item.minutes,0);$('#stat-read').textContent=read;$('#stat-favorites').textContent=favs;$('#stat-minutes').textContent=minutes}
function showProgress(progress=getJSON(progressKey)){const valid=progress&&Number.isInteger(progress.chapter)&&progress.chapter>=0&&progress.chapter<publishedChapters.length,chapter=valid?progress.chapter:0,ratio=valid?Math.min(1,Math.max(0,Number(progress.ratio)||0)):0,item=publishedChapters[chapter];$('#progress-label').textContent=valid?`${readChapters().size} de ${publishedChapters.length} capítulos completados`:'Aún no has comenzado';$('#progress-chapter').textContent=`Capítulo ${String(chapter+1).padStart(2,'0')} · ${item?.title||''}`;$('#progress-bar').style.width=`${Math.round(ratio*100)}%`;$('#progress-percent').textContent=`${Math.round(ratio*100)}% del capítulo`;$('#progress-date').textContent=valid?`Última lectura: ${new Intl.DateTimeFormat('es',{dateStyle:'medium'}).format(progress.updatedAt||Date.now())}`:'';$('#continue-reading').textContent=valid?'Continuar leyendo':'Comenzar a leer';updateStats()}
function storeProgress(ratio=0){const safeRatio=Math.min(1,Math.max(0,ratio));if(safeRatio>=.96){const read=readChapters();read.add(activeChapter);setJSON(readKey,[...read])}const progress={chapter:activeChapter,ratio:safeRatio,updatedAt:Date.now()};setJSON(progressKey,progress);showProgress(progress);renderLibrary();dockBar.style.width=`${Math.round(safeRatio*100)}%`;dockPercent.textContent=`${Math.round(safeRatio*100)}%`}
function openSavedProgress(){const saved=getJSON(progressKey),chapter=saved?.chapter??0,ratio=saved?.ratio??0;renderChapter(chapter,true,ratio)}
function renderLibrary(){const query=chapterSearch.value.trim().toLocaleLowerCase('es'),cards=publishedChapters.map((item,index)=>({item,index})).filter(({item,index})=>{const number=index+1,range=activeFilter==='all'||(activeFilter==='favorites'&&isFavorite(index))||(activeFilter==='unread'&&!isRead(index))||(activeFilter==='1-20'&&number<=20)||(activeFilter==='21-40'&&number>=21&&number<=40)||(activeFilter==='41-60'&&number>=41&&number<=100);return range&&(!query||String(number).includes(query)||item.title.toLocaleLowerCase('es').includes(query))});chapterGrid.innerHTML=cards.map(({item,index})=>`<button class="chapter-item" data-chapter="${index}">${index>=publishedChapters.length-3?'<span class="new-badge">NUEVO</span>':''}<span class="number">${String(index+1).padStart(2,'0')}</span><span><strong>${escapeHTML(item.title)}</strong><small>${item.minutes} min${isFavorite(index)?' · Favorito':''}${chapterArt[index]?' · Ilustrado':''}</small></span><span class="state">${chapterState(index)}</span></button>`).join('');chapterEmpty.hidden=cards.length>0;$$('.chapter-item').forEach(button=>button.addEventListener('click',()=>{renderChapter(Number(button.dataset.chapter),true);storeProgress(0)}))}

function applySettings(){const settings=getJSON(settingsKey,{font:18,spacious:false,wide:false,theme:'light'});document.documentElement.style.setProperty('--reader-size',`${Math.max(15,Math.min(24,settings.font))}px`);$('#leer').classList.toggle('spacious',!!settings.spacious);$('#leer').classList.toggle('wide',!!settings.wide);site.classList.toggle('dark',settings.theme==='dark');site.classList.toggle('sepia',settings.theme==='sepia');$('#reading-theme').value=settings.theme;$('#theme').textContent=settings.theme==='dark'?'☀':'☾'}
function updateSettings(patch){setJSON(settingsKey,{...getJSON(settingsKey,{font:18,spacious:false,wide:false,theme:'light'}),...patch});applySettings()}
function renderFeedback(){const reactions=getJSON(reactionKey,{}),current=reactions[activeChapter]||'',notes=getJSON(notesKey,{});$$('#reaction-buttons button').forEach(button=>{const selected=button.dataset.reaction===current;button.classList.toggle('active',selected);button.querySelector('span').textContent=selected?'1':'0'});$('#chapter-note').value=notes[activeChapter]||'';$('#note-status').textContent=''}
function initialize(chapters){publishedChapters=chapters.slice(0,100);chapterSelect.innerHTML=publishedChapters.map((item,index)=>`<option value="${index}">${String(index+1).padStart(2,'0')} · ${escapeHTML(item.title)}</option>`).join('');renderChapter(0);showProgress();renderLibrary();applySettings()}
function manuscriptChapters(markdown){const markers=[...markdown.matchAll(/^# Capítulo (\d+)\r?$/gm)];return markers.map((marker,index)=>{const block=markdown.slice(marker.index,markers[index+1]?.index??markdown.length).replace(/\r/g,''),title=(block.match(/^## (.+)$/m)||[])[1]||`Capítulo ${marker[1]}`,body=block.slice(block.indexOf(`## ${title}`)+title.length+3).replace(/\n---\s*$/,'').trim(),paragraphs=body.split(/\n\s*\n/).map(text=>text.trim()).filter(text=>text&&text!=='---').map(text=>text.replace(/^\*\*(.+)\*\*$/,'$1'));return{title,minutes:Math.max(2,Math.ceil(body.split(/\s+/).length/190)),paragraphs}})}

chapterSelect.addEventListener('change',()=>{renderChapter(Number(chapterSelect.value),true);storeProgress(0)});previous.addEventListener('click',()=>{if(activeChapter>0){renderChapter(activeChapter-1,true);storeProgress(0)}});next.addEventListener('click',()=>{if(activeChapter<publishedChapters.length-1){renderChapter(activeChapter+1,true);storeProgress(0)}});save.addEventListener('click',()=>{const key=`chapter${activeChapter+1}`;localStorage.setItem(key,isFavorite(activeChapter)?'':'saved');refreshFavoriteButton();renderLibrary();updateStats()});$('#continue-reading').addEventListener('click',openSavedProgress);$('#hero-continue').addEventListener('click',openSavedProgress);$('#clear-progress').addEventListener('click',()=>{localStorage.removeItem(progressKey);localStorage.removeItem(readKey);showProgress(null);renderLibrary()});chapterSearch.addEventListener('input',renderLibrary);
$$('.chapter-filters button').forEach(button=>button.addEventListener('click',()=>{activeFilter=button.dataset.range;$$('.chapter-filters button').forEach(item=>item.classList.toggle('active',item===button));renderLibrary()}));$('#font-down').addEventListener('click',()=>updateSettings({font:(getJSON(settingsKey,{font:18}).font||18)-1}));$('#font-up').addEventListener('click',()=>updateSettings({font:(getJSON(settingsKey,{font:18}).font||18)+1}));$('#line-toggle').addEventListener('click',()=>updateSettings({spacious:!getJSON(settingsKey,{}).spacious}));$('#width-toggle').addEventListener('click',()=>updateSettings({wide:!getJSON(settingsKey,{}).wide}));$('#reading-theme').addEventListener('change',event=>updateSettings({theme:event.target.value}));$('#theme').addEventListener('click',()=>updateSettings({theme:site.classList.contains('dark')?'light':'dark'}));$('#dock-index').addEventListener('click',()=>$('#capitulos').scrollIntoView({behavior:'smooth'}));$('#dock-next').addEventListener('click',()=>{if(activeChapter<publishedChapters.length-1){renderChapter(activeChapter+1,true);storeProgress(0)}});
$$('#reaction-buttons button').forEach(button=>button.addEventListener('click',()=>{const reactions=getJSON(reactionKey,{}),selected=reactions[activeChapter]===button.dataset.reaction;reactions[activeChapter]=selected?'':button.dataset.reaction;setJSON(reactionKey,reactions);renderFeedback()}));$('#chapter-note').addEventListener('input',event=>{clearTimeout(noteTimer);$('#note-status').textContent='Guardando…';noteTimer=setTimeout(()=>{const notes=getJSON(notesKey,{});notes[activeChapter]=event.target.value;setJSON(notesKey,notes);$('#note-status').textContent='Nota guardada en este dispositivo';},450)});
let progressTimer;addEventListener('scroll',()=>{clearTimeout(progressTimer);progressTimer=setTimeout(()=>{const rect=chapterView.getBoundingClientRect(),start=rect.top+scrollY-105,end=start+Math.max(1,chapterView.offsetHeight-innerHeight*.45),ratio=(scrollY-start)/(end-start),inReader=rect.bottom>90&&rect.top<innerHeight*.8;dock.classList.toggle('visible',inReader);if(ratio>=0&&ratio<=1.15)storeProgress(ratio)},160)},{passive:true});
if(Array.isArray(window.CHAPTERS)&&window.CHAPTERS.length)initialize(window.CHAPTERS);else fetch('manuscrito.md').then(response=>response.text()).then(markdown=>initialize(manuscriptChapters(markdown))).catch(()=>{chapterView.innerHTML='<p>No fue posible cargar los capítulos. Intenta actualizar la página.</p>'});if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
